config/routes.rb
Rails.application.routes.draw do
  get 'players/index'

  resources :players

  root 'players#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
  	@players = Player.all

  end

  def new
  	@player = Player.new
  end

  def create
  	@player = Player.new(post_params)

  	if @player.save
  		redirect_to root_path
  	end
  end

  def show 
  	@player = Player.find_by(id: params[:id])
  end

  def edit
  	@player = Player.find_by(id: params[:id])
  end

  def update
  	@player = Player.find_by(id: params[:id])
  	@player.update(player_params)
  	if @player.save
  	redirect_to	player_path(@player.id)
  end
  end

  def destroy
  @player = Player.find_by(id: params[:id])
  @player.destroy
  redirect_to root_path
  end

  private
  def post_params
  	params.require(:player).permit(:nickname, :rank, :charisma, :wisdom)
   
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/index.html.erb
<%= link_to 'Create', new_player_path %>
<% if @players == [] %>
     <p>We can't open any players</p>

 <% else %>
 <% @players.each do |post| %>
 	<p>User <b><%= player.nickname %></b> Write <br />
 	<%= player.rank %><br>
 	<%= player.charisma %><br>
 	<%= player.wisdom %><br>

 	<%= link_to 'read more ',player_path(post.id) %> </p>
 	<% end %>

 <%end %>

app/views/players/new.html.erb
<%= form_for @player, url: players_path  do |f| %>
   <%= f.text_field :nickname %><br>
  <%= f.int_field :rank %><br>
  <%= f.int_area :charisma, wisdom: "60x12" %>
  <%= f.submit "Create" %>
<% end %>

app/views/players/player.html.erb
<%= form_for @player, url: player_path(@player.id)  do |f| %>
   <%= f.text_field :nickname %><br>
  <%= f.int_field :rank %><br>
  <%= f.int_field :charisma,wisdom: "60x12" %>
  <%= f.submit "Edit" %>
<% end %>

app/views/players/show.html.erb
<p>
	<%= @player.username %> write post: <br />
	Player: <%= @player.rank %><br />
	Charisma: <%= @player.charisma %><br />
</p>

<p>
	<%= link_to 'Edit', edit_player_path(@player.id) %><br />
	<%= link_to 'Destroy',player_path(@player.id), method: :delete %>
</p>